### ISSUE TITLE
How to always run usbctl automatically?

### ISSUE THREAD

**Issue by Utini2000** [anthraxx/usbctl#10]
Hey there,
I just found this nice secure tool and so far it works great. 
How ever, I noticed that the protection is gone after a reboot.
How to always keep it active or run it automatically on boot up e.g. with a previously saved whitelist?

**Comment by kpcyrd** [comment]
Assuming you're on archlinux and you've installed the usbctl package you can simply run:
```
systemctl enable deny-new-usb
```
This is going to accept all usb devices that are present during the boot and then deny all new devices after the boot finished.

**Comment by Utini2000** [comment]
Ah thanks, and is there a way to add something to a permanent whitelist?

E.g. my usually external HDD that I connect via USB. Or my laptops tochpad which might be disabled on boot up because a mouse was connected (but the touchpad gets activated if I unplug the mouse at a later point).

**Comment by kpcyrd** [comment]
Unfortunately there's no way to whitelist devices because the deny-new-usb kernel patch filters directly on the "new device has been inserted" event. This is to keep the attack surface as low as possible by blocking a device before any communication with the device happened and therefore why no device identifier is known that we could use to filter.

I think there's a different project called [USBGuard](https://github.com/USBGuard/usbguard) but please be aware that a device can bruteforce identifiers until one is accepted.
